# Generated by Django 3.0.4 on 2020-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('roll_no', models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=15)),
            ],
        ),
    ]
