# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_auto_20200702_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
