# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0005_auto_20200703_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_grade',
            name='sg',
            field=models.ForeignKey(default='ankit', on_delete=django.db.models.deletion.CASCADE, related_name='s_g', to='student_api.student_info'),
        ),
    ]
